jwt:
    secret: javainuse
spring:
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    datasource:
        password: India@123
        platform: mysql
        url: jdbc:mysql://localhost/auth?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
        username: root
    jpa:
        hibernate:
            ddl-auto: create-drop
server:
    port: 8081
