jwt:
    get:
        token:
            uri: /authenticate
    secret: javainuse
server:
    port: 8081
#spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        password: India@123
#        url: jdbc:mysql://localhost:3306/auth?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
#        username: root
#    jpa:
#        database-platform: org.hibernate.dialect.MySQL5Dialect
#        hibernate:
#            console:
#                enabled: true
#            ddl-auto: update
#            format_sql: true
#        show-sql: true
